server:
  port: 8080

spring:
  application:
    name: ms-stadium
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ms_stadium_db}
    username: ${SPRING_DATASOURCE_USERNAME:ms_auth_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ms_auth_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:clave}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html